export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_START: 'cartegory/FETCH_CATEGORIES_START',
  FETCH_CATEGORIES_SUCCESS: 'cartegory/FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILED: 'cartegory/FETCH_CATEGORIES_FAILED',
};
